server:
  port: 7777
  servlet:
    context-path: /iot
spring:
  application:
    name: iot
  datasource:
    url: jdbc:mysql://49.233.131.191:3306/iot?characterEncoding=utf-8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: root
    password: ChTYg3TJTYKQYk41
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: true

#MQTT server
mqtt:
  host: tcp://www.dpnice.online:1883
  username: test
  password: test
  clientId: mqtt|client|v3|spring
  cleanStart: false
  topic: esp32-test/t&h&w
  qos: 0

alarm:
  #适宜湿度区间
  humidity: "[50,70]"
  #适宜温度区间
  temperature: "[16,25]"
  water: 10

logging:
  level:
    root: info
    com.dpnice.iot.tutu.handle.THWHandle: debug
